language: java

jdk:
    - oraclejdk8
    - oraclejdk7

git:
    depth: 3

before_script:
    - chmod +x gradlew

script:
    - echo 'Setup environment'
    - ./gradlew setupCiWorkspace
    - echo 'Build'
    - ./gradlew build

